//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoListManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoList
    {
        public int Todo_id { get; set; }
        public string Todo_title { get; set; }
        public System.DateTime Add_date { get; set; }
        public string Todo_contents { get; set; }
        public string Adding_member { get; set; }
    }
}
